services:
  - type: web
    name: star-house
    env: node
    plan: free
    startCommand: node server.js
    buildCommand: npm install
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: FORMSPREE_ENDPOINT
        sync: false
